### ISSUE TITLE
Drupal machine names can start with numbers

### ISSUE THREAD

**Issue by Leksat** [drupal-graphql/graphql#183]
and GrpahQL names should always start with a letter.
This needs to be considered when translating Drupal machine name into a GraphQL name.

For example, currently, I can create a view with machine name 1. And the schema will be broken:
```Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "1Graphql1View" does not.```

**Comment by fubhy** [comment]
https://github.com/fubhy/graphql-drupal/pull/279

**Comment by weitzman** [comment]
Maybe this regressed? I'm using latest dev and getting:

```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "3UpRows" does not.
    at invariant (http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:18938:11)
    at assertValidName (http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:25827:27)
    at http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:24069:42
    at Array.forEach (<anonymous>)
    at defineFieldMap (http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:24068:14)
    at GraphQLObjectType.getFields (http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:24025:46)
    at http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:25497:27
    at typeMapReducer (http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:25509:7)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:25377:34)
    at buildClientSchema (http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:26620:10)
    at http://cdn.jsdelivr.net/graphiql/0.7.0/graphiql.js:1601:55
```

**Comment by weitzman** [comment]
woops. my module was out of date. sorry.
