### ISSUE TITLE
Explorer/Voyager: TypeError: Argument 2 passed to Drupal\graphql\GraphQL\Execution\Processor::deferredResolve() must be callable

### ISSUE THREAD

**Issue by drupov** [drupal-graphql/graphql#467]
Just installed a vanilla drupal with `drupal-composer/drupal-project` and made a `composer require drupal/graphql` inside the project. Everything went fine with Drupal installation and graphql and graphql_core module enabling, but I cannot get to both `graphql/explorer` or `graphql/voyager`("The website encountered an unexpected error. Please try again later."). 

The log shows identical error messages for both cases though:
```
TypeError: Argument 2 passed to Drupal\graphql\GraphQL\Execution\Processor::deferredResolve() must be callable, object given, called in /var/www/html/backend/vendor/youshido/graphql/src/Execution/Processor.php on line 516 in Drupal\graphql\GraphQL\Execution\Processor->deferredResolve() (line 79 of /var/www/html/backend/web/modules/contrib/graphql/src/GraphQL/Execution/Processor.php)
#0 /var/www/html/backend/vendor/youshido/graphql/src/Execution/Processor.php(516): Drupal\graphql\GraphQL\Execution\Processor->deferredResolve(Object(Drupal\graphql\GraphQL\Schema\Schema), Object(Youshido\GraphQL\Introspection\Field\SchemaField), Object(Closure))
#1 /var/www/html/backend/vendor/youshido/graphql/src/Execution/Processor.php(200): Youshido\GraphQL\Execution\Processor->resolveObject(Object(Youshido\GraphQL\Introspection\Field\SchemaField), Object(Youshido\GraphQL\Parser\Ast\Query), NULL)
#2 /var/www/html/backend/vendor/youshido/graphql/src/Execution/Processor.php(162): Youshido\GraphQL\Execution\Processor->resolveField(Object(Youshido\GraphQL\Field\Field), Object(Youshido\GraphQL\Parser\Ast\Query))
#3 /var/www/html/backend/vendor/youshido/graphql/src/Execution/Processor.php(93): Youshido\GraphQL\Execution\Processor->resolveQuery(Object(Youshido\GraphQL\Parser\Ast\Query))
#4 /var/www/html/backend/web/modules/contrib/graphql/src/GraphQL/Execution/QueryProcessor.php(93): Youshido\GraphQL\Execution\Processor->processPayload(' query Intro...', Array)
#5 /var/www/html/backend/web/modules/contrib/graphql/src/GraphQL/Utility/Introspection.php(131): Drupal\graphql\GraphQL\Execution\QueryProcessor->processQuery('default', ' query Intro...')
#6 /var/www/html/backend/web/modules/contrib/graphql/src/Controller/ExplorerController.php(77): Drupal\graphql\GraphQL\Utility\Introspection->introspect('default')
#7 [internal function]: Drupal\graphql\Controller\ExplorerController->viewExplorer('default')
#8 /var/www/html/backend/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#9 /var/www/html/backend/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#10 /var/www/html/backend/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#11 /var/www/html/backend/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#12 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#13 /var/www/html/backend/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array)
#14 /var/www/html/backend/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/www/html/backend/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/www/html/backend/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /var/www/html/backend/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /var/www/html/backend/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /var/www/html/backend/web/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /var/www/html/backend/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#25 {main}.
--
```

There are also warning messages:
```
Warning: Declaration of Drupal\graphql\GraphQL\Execution\Processor::deferredResolve($resolvedValue, callable $callback) should be compatible with Youshido\GraphQL\Execution\Processor::deferredResolve($resolvedValue, Youshido\GraphQL\Field\FieldInterface $field, callable $callback) in require() (line 19 of /var/www/html/backend/web/modules/contrib/graphql/src/GraphQL/Execution/Processor.php)
#0 /var/www/html/backend/web/core/includes/bootstrap.inc(566): _drupal_error_handler_real(2, 'Declaration of ...', '/var/www/html/b...', 19, Array)
#1 /var/www/html/backend/web/modules/contrib/graphql/src/GraphQL/Execution/Processor.php(19): _drupal_error_handler(2, 'Declaration of ...', '/var/www/html/b...', 19, Array)
#2 /var/www/html/backend/vendor/symfony/class-loader/ApcClassLoader.php(110): require('/var/www/html/b...')
#3 [internal function]: Symfony\Component\ClassLoader\ApcClassLoader->loadClass('Drupal\\graphql\\...')
#4 /var/www/html/backend/web/modules/contrib/graphql/src/GraphQL/Execution/QueryProcessor.php(92): spl_autoload_call('Drupal\\graphql\\...')
#5 /var/www/html/backend/web/modules/contrib/graphql/src/GraphQL/Utility/Introspection.php(131): Drupal\graphql\GraphQL\Execution\QueryProcessor->processQuery('default', ' query Intro...')
#6 /var/www/html/backend/web/modules/contrib/graphql/src/Controller/ExplorerController.php(77): Drupal\graphql\GraphQL\Utility\Introspection->introspect('default')
#7 [internal function]: Drupal\graphql\Controller\ExplorerController->viewExplorer('default')
#8 /var/www/html/backend/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array)
#9 /var/www/html/backend/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#10 /var/www/html/backend/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#11 /var/www/html/backend/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
#12 [internal function]: Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}()
#13 /var/www/html/backend/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Object(Closure), Array)
#14 /var/www/html/backend/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#15 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#16 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#17 /var/www/html/backend/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(99): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#18 /var/www/html/backend/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(78): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#19 /var/www/html/backend/vendor/asm89/stack-cors/src/Asm89/Stack/Cors.php(49): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#20 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#21 /var/www/html/backend/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(50): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#22 /var/www/html/backend/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#23 /var/www/html/backend/web/core/lib/Drupal/Core/DrupalKernel.php(657): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#24 /var/www/html/backend/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#25 {main}.
```

That's Drupal 8.4.4 and PHP 7.1.12

I tried several things already (mostly playing around with versions), but cannot get it to work. Any ideas?

**Comment by xuxucode** [comment]
There is a broken change since `youshido/graphql:1.5.3`.
Try `composer require youshido/graphql:1.5.2`

**Comment by drupov** [comment]
Thanks, that's it. I created a pull request for that #468
