### ISSUE TITLE
setCurrentUser() must implement interface Drupal\Core\Session\AccountInterface, null given

### ISSUE THREAD

**Issue by edmargomes** [drupal-graphql/graphql#833]
Drupal 8.7.3 and GraphQl 8.4 alpha1
```
api_php   | [29-Jun-2019 16:40:07] WARNING: [pool www] child 85 said into stderr: "NOTICE: PHP message: TypeError: Argument 1 passed to Drupal\language\LanguageNegotiationMethodBase::setCurrentUser() must implement interface Drupal\Core\Session\AccountInterface, null given, called in /var/www/html/web/core/modules/language/src/LanguageNegotiator.php on line 213 in /var/www/html/web/core/modules/language/src/LanguageNegotiationMethodBase.php on line 52 #0 /var/www/html/web/core/modules/language/src/LanguageNegotiator.php(213): Drupal\language\LanguageNegotiationMethodBase->setCurrentUser(NULL)"
api_php   | [29-Jun-2019 16:40:07] WARNING: [pool www] child 85 said into stderr: "#1 /var/www/html/web/modules/contrib/graphql/src/EventSubscriber/OperationSubscriber.php(43): Drupal\language\LanguageNegotiator->getNegotiationMethodInstance('language-graphq...')"
api_php   | [29-Jun-2019 16:40:07] WARNING: [pool www] child 85 said into stderr: "#2 [internal function]: Drupal\graphql\EventSubscriber\OperationSubscriber->onBeforeOperation(Object(Drupal\graphql\Event\OperationEvent), 'graphql.operati...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))"
api_php   | [29-Jun-2019 16:40:07] WARNING: [pool www] child 85 said into stderr: "#3 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatc..."
api_php   | 172.18.0.9 -  29/Jun/2019:16:40:07 +0000 "GET /index.php" 500

**Comment by fubhy** [comment]
Hi there, please check out the latest 8.x-4.x-dev version. This should already be fixed after https://github.com/drupal-graphql/graphql/commit/27f8a493b746e236529a631d388ae507c50c5e0d

**Comment by edmargomes** [comment]
Hi @fubhy 
I tried to use the dev version but failed to load the schemas in the interface.

So I did this alpha test and it worked for me:
Line 30:
![image](https://user-images.githubusercontent.com/6574942/60387238-73bb8b80-9a76-11e9-82ac-87e6af023fd5.png)

Now, Explorer and Voyager open for me in the alpha version

**Comment by fubhy** [comment]
Did you try to install just the examples module (graphql_examples) and check out the schema there?

**Comment by edmargomes** [comment]
No, I'm going to test the dev version again in 10 minutes and enable the example module

**Comment by edmargomes** [comment]
Sorry @fubhy , you  are correct, everything is working here with the news commits

**Comment by fubhy** [comment]
Perfect, glad to hear that :-)

**Comment by fubhy** [comment]
Feel free to join our #graphql channel in the Drupal slack for convenient support :-)
