### ISSUE TITLE
Error "Type Query must define one or more fields." with Apollo Gateway

### ISSUE THREAD

**Issue by Kwadz** [drupal-graphql/graphql#886]
I'm using the GraphQL module, version 8.x-4.x, to run a federated query through [Apollo Federation Demo](https://github.com/apollographql/federation-demo), that's failing with the following error:

```
Encountered error when loading content at http://localhost:8000/graphql: request to http://localhost:8000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:8000
(node:1) UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: Type Query must define one or more fields.
    at ApolloGateway.createSchema (/usr/src/app/node_modules/@apollo/gateway/dist/index.js:106:19)
    at ApolloGateway.<anonymous> (/usr/src/app/node_modules/@apollo/gateway/dist/index.js:96:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/@apollo/gateway/dist/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Guys from Apollo are wondering if it comes from the gateway or not. Anyway, apparently empty Query type is not valid, see https://github.com/apollographql/apollo-server/issues/3100.

**Comment by Kwadz** [comment]
@pmelab, you added the wrong label, should be 4.x.

**Comment by Kwadz** [comment]
Interesting information from https://github.com/apollographql/apollo-server/issues/3419:

> The downstream services in a federated architecture must implement [the federation specification](https://www.apollographql.com/docs/apollo-server/federation/federation-spec/).
> Many GraphQL servers have already implemented the federated specification already, including graphql-java, Ariadne, **WPGraphQL** and Graphene (via graphene-federation). 

Is it implemented on Drupal GraphQL?
